# Generated by Django 5.1.2 on 2024-10-26 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('nationality', models.CharField(choices=[('FR', 'French'), ('US', 'American')], max_length=2)),
                ('political_orientation', models.CharField(choices=[('L', 'Liberal'), ('C', 'Conservative')], max_length=1)),
                ('religion', models.CharField(choices=[('CH', 'Christianity'), ('IS', 'Islam')], max_length=2)),
                ('ethnicity', models.CharField(choices=[('C', 'Caucasian'), ('A', 'Asian')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
