# Generated by Django 5.1.2 on 2024-11-12 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profile_ethnicity_alter_profile_nationality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('bookmark', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('share_platform', models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('x', 'X'), ('instagram', 'Instagram'), ('zhatsapp', 'Whatsapp')], max_length=50, null=True)),
                ('share_to', models.CharField(blank=True, choices=[('friends', 'Friends'), ('family', 'Family')], max_length=50, null=True)),
                ('credibility_score', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='api.profile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='api.post')),
            ],
        ),
    ]
