# Generated by Django 5.1.2 on 2024-11-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20241112_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='share_platform',
            field=models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('x', 'X'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp')], max_length=50, null=True),
        ),
    ]
