# Generated by Django 5.1.2 on 2024-11-12 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_interaction_share_platform'),
    ]

    operations = [
    ]
