# Generated by Django 5.1.2 on 2024-11-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile_has_completed_experiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='time_spent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interaction',
            name='watched_twice',
            field=models.BooleanField(default=False),
        ),
    ]
