# Generated by Django 5.1.2 on 2024-11-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_profile_nationality_profile_citizenship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='watch_durations',
            field=models.JSONField(default=list),
        ),
    ]
