# Generated by Django 5.1.2 on 2024-11-25 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_interaction_watch_durations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='watched_twice',
        ),
    ]
