# Generated by Django 5.1.2 on 2024-11-25 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_adminsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
